const detail = document.querySelector('#project-detail');
const description = document.querySelector('meta[name="description"]');
const projectId = new URLSearchParams(window.location.search).get('project');
const project = (window.PORTFOLIO_PROJECTS || []).find(({ id }) => id === projectId);
const primary = 'inline-flex min-h-12 items-center bg-slate-900 px-5 text-sm font-semibold text-white transition-colors hover:bg-teal-900 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-teal-800';
const secondary = 'text-sm font-semibold text-slate-600 underline decoration-slate-300 underline-offset-6 transition-colors hover:text-teal-800 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-teal-800';

const externalLink = (url, label, ariaLabel, className) => url ? `<a class="${className}" href="${url}" target="_blank" rel="noreferrer" aria-label="${ariaLabel}">${label} <span aria-hidden="true">↗</span></a>` : '';

if (!project) {
  document.title = 'Project not found — Chandra Aditiya Putra';
  description.content = 'The requested project is not available in the portfolio of Chandra Aditiya Putra.';
  detail.innerHTML = `<div class="max-w-3xl"><p class="text-xs font-semibold tracking-[0.14em] text-teal-800 uppercase">404 / Project not found</p><h1 class="mt-6 font-display text-5xl leading-[.95] font-semibold tracking-[-0.06em] sm:text-7xl">Project not found.</h1><p class="mt-6 max-w-xl text-lg leading-8 text-slate-600">This project link is no longer available or has not been registered.</p><a class="${primary} mt-9" href="index.html#project">Back to projects <span class="ml-8" aria-hidden="true">↗</span></a></div>`;
} else {
  document.title = `${project.title} — Chandra Aditiya Putra`;
  description.content = project.summary;
  detail.innerHTML = `<article><div class="max-w-3xl"><p class="text-xs font-semibold tracking-[0.14em] text-teal-800 uppercase">Project ${project.number} / ${project.category}</p><h1 class="mt-6 font-display text-5xl leading-[.95] font-semibold tracking-[-0.06em] sm:text-7xl">${project.title}</h1><p class="mt-7 max-w-2xl text-lg leading-8 text-slate-600">${project.summary}</p><div class="mt-9 flex flex-wrap items-center gap-4">${externalLink(project.github, 'Open GitHub', 'Open GitHub repository', primary)}${externalLink(project.demo, 'Live website', 'Open live website', secondary)}${externalLink(project.playStore, 'Play Store', 'Open Google Play listing', secondary)}${externalLink(project.proposal, 'Open proposal', 'Open project proposal', secondary)}</div></div><dl class="mt-20 grid gap-px border border-slate-200 bg-slate-200 md:grid-cols-2"><div class="bg-stone-50 p-6"><dt class="text-xs tracking-[0.12em] text-slate-500 uppercase">Problem</dt><dd class="mt-4 text-sm leading-7 text-slate-600">${project.problem}</dd></div><div class="bg-stone-50 p-6"><dt class="text-xs tracking-[0.12em] text-slate-500 uppercase">Solution</dt><dd class="mt-4 text-sm leading-7 text-slate-600">${project.solution}</dd></div></dl><div class="mt-12 grid gap-10 border-t border-slate-200 pt-10 md:grid-cols-2"><div><p class="text-xs tracking-[0.12em] text-slate-500 uppercase">My Role</p><h2 class="mt-4 font-display text-3xl font-semibold tracking-tight">${project.role}</h2><p class="mt-5 max-w-xl text-sm leading-7 text-slate-600">${project.note}</p></div><div><p class="text-xs tracking-[0.12em] text-slate-500 uppercase">Tech Stack</p><ul class="mt-4 flex flex-wrap gap-2">${project.stack.map((item) => `<li class="border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700">${item}</li>`).join('')}</ul></div></div><section class="mt-12 border-t border-slate-200 pt-10" aria-labelledby="technical-highlights"><p id="technical-highlights" class="text-xs tracking-[0.12em] text-slate-500 uppercase">Technical Highlights</p><ul class="mt-5 grid gap-3 text-sm leading-7 text-slate-600 sm:grid-cols-2">${project.highlights.map((item) => `<li class="border-l-2 border-teal-800 pl-3">${item}</li>`).join('')}</ul></section><nav class="mt-20 flex flex-wrap gap-x-7 gap-y-4 border-t border-slate-200 pt-6 text-sm font-semibold"><a class="transition-colors hover:text-teal-800 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-teal-800" href="index.html#project">← Back to all projects</a><a class="transition-colors hover:text-teal-800 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-teal-800" href="mailto:chandraaditiyaputra80@gmail.com">Discuss this project ↗</a></nav></article>`;
}
